title:            Yi-Xin LIU
description:      "Dr. Yi-Xin Liu is a lecturer and researcher working in the field of polymer physics at Fudan University. He currently is working at MRL@UCSB as a visiting researcher."
disqus_shortname: ngpy.org
reading_time:     true
words_per_minute: 200
url:                    # blank for local preview
#url: http://ngpy.org   # for production
header-img: images/about-bg.jpg

# Owner/author information
owner:
  name:           Yi-Xin Liu
  avatar:         avatar.jpg
  bio:            "Dr. Yi-Xin Liu is a lecturer and researcher working in the field of polymer physics at Fudan University. He currently is also working at MRL@UC Santa Barbara as a visiting researcher."
  email:          lyx@fudan.edu.cn
  # Social networking links used in footer. Update and remove as you like.
  twitter: lyxfudan
  facebook:
  github: liuyxpp
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +liuyxpp

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: liuyxpp
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# http://jekyllrb.com/docs/permalinks/
permalink:   /:year/:month/:title  #/:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
